import Head from 'next/head';
import Tiptap from '../components/Tiptap';
import { useForm } from "react-hook-form";

export default function Home() {
  
  const [user, setUser] = useState();

  const { register, handleSubmit } = useForm();
  
  const onSubmit = (data) => {
    
    let randomColor = Math.floor(Math.random()*16777215).toString(16)  
    let color = "#" + randomColor;
    
    const newUser = {
      userName: data.name,
      color
    };
    setUser(newUser);
  }
  
  return (
    <>
      <Head>
        <title>TipTap App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      {
        user ? (
          <Tiptap user={user}/>
        ) : (
          <form onSubmit={handleSubmit(onSubmit)}>
            <input {...register('name', { required: true })} />
            <button type="submit">Create User</button>
          </form>
        )
      }
      </main>
    </>
  )
}
